### ISSUE TITLE
Unable to import singlefile .html files

### ISSUE THREAD

**Issue by Xurbax** [rauenzi/Trilium-SingleFile#1]
Running Trilium 0.60.4, I have imported Trilium SingleFile into Trilium, successfully as far as I can tell (safe option unchecked).
Added a note/folder "inbox" with the tag #singleFileInbox.
Dragging any .html file saved by SingleFile to the drag-n-drop box seems to work and after a moment shows up at the bottom of the box with a green checkmark, but nothing ever shows up in the "inbox". Any hint as to what I am doing wrong?
Moving the "inbox" note to the top level, the same level as Trilium SingleFile, or under Trillium SingleFile makes no difference.
SingleFile version used is 1.21.66, under Chrome (though I can't see how this would matter).

Thanks.

**Comment by zerebos** [comment]
You can check some other places in the tree that it might have defaulted to such as your regular `#inbox` or your daily note. If it's not in either of those places, I would recommend making a temporary JS Frontend note and putting in this:
```js
api.searchForNotes("#singleFileSource").then(nl => {
    console.log(nl);
    api.showMessage(`You currently have ${nl.length} SingleFile pages!`);
});
```
When you run that you should see a toast telling you the number of SingleFile pages stored. If it's not 0, then check console for some details on where they might be stored. You can provide screenshots of any/all of it here if you want help debugging.

**Comment by Jayy001** [comment]
![image](https://github.com/rauenzi/Trilium-SingleFile/assets/56607897/8cdab7c8-a4ef-4c83-b338-102d4dd6a1f2)
I'm having the exact same problem, imported multiple - gives a check mark but nothing has been imported. Fresh trillium install with no notes except for a custom theme (Blue-theme)
