### ISSUE TITLE
How to make the label automatically change to pageurl

### ISSUE THREAD

**Issue by SiriusXT** [rauenzi/Trilium-SingleFile#2]
How to make the label automatically change to pageurl, so that it can quickly jump to the browser to open it

**Comment by zerebos** [comment]
I'm assuming you mean instead of using the `url` attribute?

**Comment by SiriusXT** [comment]
Yes, I want to change the automatically added url attribute to pageUrl

> I'm assuming you mean instead of using the `url` attribute?

**Comment by zerebos** [comment]
To be honest, I thought I had changed it back to `pageUrl`... I only realized it was `url` when you said something. I should fix that. I will also provide a script to fix/convert all existing ones and potentially add a setting.

**Comment by zerebos** [comment]
@SiriusXT Sorry this is so late, but I've finally released a new update that includes this change. You'll also find a runner in the plugin's settings to automatically update old `#url` to new `#pageUrl` though both will still work with the new renderer (for now).

Make sure to follow the updating instructions in the README!
