### ISSUE TITLE
Not working on newest version of Trilium 0.61.14

### ISSUE THREAD

**Issue by xnohat** [rauenzi/Trilium-SingleFile#3]
Hi, 

Singlefile suddenly stop working after version trilium 0.61.14 is there any bug ?
When I drag html file on Web version of Trilium to Singlefile Trilium it not detect drop event and open drop file on browser
when i drag on Desktop version, nothing create as before.

https://github.com/rauenzi/Trilium-SingleFile/assets/4613808/499d9796-2a1c-424b-9a67-0f097e5217d0

Thanks,

**Comment by zerebos** [comment]
I will look into this

**Comment by zerebos** [comment]
So it looks like newer versions of trilium are intercepting the drop event... Will have to think of a good workaround.

**Comment by Simon-CR** [comment]
was any progress done on this one ?  Just found your plugin and I love it, but right now it's only working with folder watch (drag-drop in safari isn't doing anything) 

thanks

**Comment by zerebos** [comment]
Hi @Simon-CR sorry for the late response, some IRL things got in the way, I am back working on things and should have a fix somewhat soon.

**Comment by zerebos** [comment]
Hey I've finally fixed this! Apparently it wasn't Trilium hijacking the event but a change in how the browser events work for file DnD
