### ISSUE TITLE
[Guide] Cannot find plugin setting

### ISSUE THREAD

**Issue by leesandao** [rauenzi/Trilium-SingleFile#6]
Open the plugins settings page
Scroll to the bottom
Click "Fix ~renderNote Attributes"

I cannot find it....

**Comment by zerebos** [comment]
Can you post screenshots, add version information, etc? This didn't give me much to go on.

**Comment by leesandao** [comment]
Thanks for your response, Trilium build is 0.63.5
![image](https://github.com/user-attachments/assets/d286cd21-6603-4052-99b3-bd078f1b179c)


Step 1. I download from github
Step 2. Import to scripts folder with "unsafe" mode
![image](https://github.com/user-attachments/assets/6aa1a2b2-e17a-4363-82cc-1234d6060f1a)
Step 3. Dont know how to go into plugins settings page...
![image](https://github.com/user-attachments/assets/d0d13d17-ef78-4541-87b6-0f14cb74c85e)

**Comment by zerebos** [comment]
I see, you just downloaded and imported the source repository, you shouldn't do that. You should grab the `.zip` from the Releases section as stated in the [installation instructions](https://github.com/rauenzi/Trilium-SingleFile?tab=readme-ov-file#installation). Here is a direct link to what you should download and import: https://github.com/rauenzi/Trilium-SingleFile/releases/download/v0.1.1/Trilium-SingleFile.zip

**Comment by leesandao** [comment]
Thanks, I tried again, it works now!!
